# Generated by Django 5.0.6 on 2024-06-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0002_alter_fieldchoice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('file', 'File')], max_length=50),
        ),
    ]
