# Generated by Django 5.0.6 on 2024-06-09 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0003_alter_field_field_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='created On'),
        ),
        migrations.AddField(
            model_name='form',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published On'),
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('maintainance', 'Pulled Down')], default='draft', max_length=50, verbose_name='Status'),
        ),
    ]
