# Generated by Django 5.0.6 on 2024-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0005_form_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
