# Generated by Django 5.0.6 on 2024-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0007_alter_field_options_fieldchoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
