# Generated by Django 5.0.6 on 2024-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0009_form_published_by_form_template_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
